feat: reject request if bot or user not signed in
abak-press/apress-api pull request #72
Opened 2024-03-27 23:19 UTC by ArtemBorodinEvgenyevich

https://jira.railsc.ru/browse/PC4-30714

2024-03-27 23:22 UTC, ArtemBorodinEvgenyevich commented on lib/apress/api/api_controller/base.rb
> +          return false if Rails.env.test?
По задаче - отклоняем запрос для ботов и НАП

Добавил такую проверку, чтобы не посыпались тесты в гемах и проектах, где есть проверка на успешный запрос к api контроллеру

2024-03-27 23:26 UTC, ArtemBorodinEvgenyevich commented
Нужна ветка pc-march-2

2024-03-27 23:27 UTC, ArtemBorodinEvgenyevich commented
@Gelani-G, @isqad

2024-03-28 04:59 UTC, isqad requested changes
И где тесты? Может все таки у себя в проекте это сделать, чем  в паблик геме?

2024-03-28 04:59 UTC, isqad commented on lib/apress/api/api_controller/base.rb
> +          request.bot? || current_user.nil? || current_user.provider_sid?
откуда тут request.bot? возьмется?

2024-03-28 04:59 UTC, isqad commented on lib/apress/api/api_controller/base.rb
> +          request.bot? || current_user.nil? || current_user.provider_sid?
и provider_sid?

2024-03-28 05:43 UTC, ArtemBorodinEvgenyevich commented
Делаем в проекте
На близко тогда потом по аналогии с нами сделаете

2024-03-28 05:43 UTC, closed without merging